---
- name: "main : Include variables"
  include_vars:
    file: "{{ ansible_facts.distribution }}.yml"

- name: "main : Import centos.yml"
  import_tasks: centos.yml
  when: ansible_facts.distribution == "CentOS"

- name: "main : Import ubuntu.yml"
  import_tasks: ubuntu.yml
  when: ansible_facts.distribution == "Ubuntu"

- name: "main : Configure nginx"
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf }}"
    backup: true
  notify: "handler : reload nginx"
  become: true

- name: "main : Enable default site"
  ansible.builtin.template:
    src: default.conf.j2
    dest: "{{ nginx_conf_dir }}/default.conf"
    backup: true
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "640"
  notify: "handler : reload nginx"
  become: true

- name: "main : Create web root directory"
  ansible.builtin.file:
    state: directory
    path: "{{ nginx_web_root }}"
  become: true

- name: "main : Create index.html page"
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_web_root }}/index.html"
    backup: true
  notify: "handler : reload nginx"
  become: true

- name: "main : Add Hello, World to molecule.html"
  ansible.builtin.lineinfile:
    state: present
    create: true
    path: "{{ nginx_web_root }}/molecule.html"
    line: "Hello, World!"
    regexp: "^Hello"
    insertafter: EOF
  become: true

- name: "main : Add host information to molecule.html"
  ansible.builtin.lineinfile:
    state: present
    create: true
    path: "{{ nginx_web_root }}/molecule.html"
    line: "My hostname is: {{ inventory_hostname }}"
    regexp: "^My hostname is"
    insertafter: EOF
  become: true

- name: "main : Start nginx"
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
